VFPPROD

-- Table  Datum Depth  Rate Type  WFR Type  GFR Type  THP Type  ALQ Type  UNITS   TAB Type
-- -----  -----------  ---------  --------  --------  --------  --------  ------  --------
       1       3000.0        GAS       WGR       GOR       THP        ''  METRIC       BHP /

-- GAS units - sm3/day ( 3 values )
     50000    500000     5e+06 /

-- THP units - barsa ( 2 values )
        40       100 /

-- WGR units - sm3/sm3 ( 2 values )
         0     1e-05 /

-- GOR units - sm3/sm3 ( 2 values )
       500      4000 /

-- '' units -  ( 1 values )
         0 /

 1  1  1  1    160.11    130.21    180.31
/
 1  1  2  1    140.12    110.22    160.32
/
 1  2  1  1    165.13    135.23    185.33
/
 1  2  2  1    145.14    115.24    165.34
/
 2  1  1  1    240.15    210.25    260.35
/
 2  1  2  1    220.16    190.26    240.36
/
 2  2  1  1    245.17    215.27    265.37
/
 2  2  2  1    225.18    195.28    245.38
/
