name: ecl2df

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
      - published
  schedule:
    # Run CI every night and check that tests are working with latest dependencies
    - cron:  '0 0 * * *'

env:
  ERT_SHOW_BACKTRACE: 1

jobs:

  ecl2df:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        python-version: ['3.6', '3.7', '3.8']

    steps:
      - name: Checkout commit locally
        uses: actions/checkout@v2

      - name: Checkout tags
        # This seems necessary for setuptools_scm to be able to infer
        # the correct version.
        run: git fetch --unshallow --tags

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}

      - name: Check code style
        run: |
          pip install black flake8
          black --check ecl2df tests setup.py docs/conf.py
          flake8 ecl2df tests

      - name: Install ecl2df with dependencies
        run: |
          pip install --upgrade pip
          pip install .
          python -c "import ecl2df"

      - name: Install test dependencies
        run: pip install .[tests,docs]

      - name: List all installed packages
        run: pip freeze

      - name: Run tests
        run: |
          python -c "import ecl2df"
          pytest tests/

      - name: Syntax check documentation
        run: |
          rstcheck -r docs

      - name: Build documentation
        run: |
          sphinx-apidoc -f -H "API for ecl2df" -o docs ecl2df
          python setup.py build_sphinx

      - name: Update GitHub pages
        if: github.repository_owner == 'equinor' && github.ref == 'refs/heads/master' && matrix.python-version == '3.6'
        run: |
            cp -R ./build/sphinx/html ../html

            git config --local user.email "ecl2df-github-action"
            git config --local user.name "ecl2df-github-action"
            git fetch origin gh-pages
            git checkout --track origin/gh-pages
            git clean -f -f -d -x
            git rm -r *

            cp -R ../html/* .

            git add .

            if git diff-index --quiet HEAD; then
              echo "No changes in documentation. Skip documentation deploy."
            else
              git commit -m "Update Github Pages"
              git push "https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" gh-pages
            fi

      - name: Build python package and publish to pypi
        if: github.event_name == 'release' && matrix.python-version == '3.6'
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.ecl2df_pypi_token }}
        run: |
          python -m pip install --upgrade setuptools wheel twine
          python setup.py sdist bdist_wheel
          twine upload dist/*
